version: '3.8'

services:
  btc-tracker:
    image: thewilqq/btc-tracker:latest
    container_name: btc-tracker-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Flexible database paths - choose one approach:
      - DATABASE_URL=file:/app/data/bitcoin-tracker.db     # Recommended: mounted volume
      # - DATABASE_URL=file:/data/bitcoin-tracker.db       # Host directory mount
      # - DATABASE_URL=postgresql://user:pass@postgres:5432/btctracker  # PostgreSQL
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-super-secure-secret-key-here-change-this}
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      # Mount data directory for flexible database storage
      - btc_data:/app/data
      # Optional: mount host directory for database
      # - /host/path/to/data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - btc-tracker-network

volumes:
  btc_data:
    driver: local

networks:
  btc-tracker-network:
    driver: bridge 