# ====================================
# BTC Tracker - Host Directory Mounting
# ====================================
# Alternative docker-compose.yml that uses host directories instead of Docker volumes
# Usage: docker-compose -f docker-compose.host-volumes.yml up -d

version: '3.8'

services:
  btc-tracker:
    image: thewilqq/btc-tracker:latest
    container_name: btc-tracker-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-super-secure-secret-key-here-change-this}
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      # Host directory mounting - data persisted on host filesystem
      - ./btc-tracker-data:/app/data              # Database: ./btc-tracker-data/btc-tracker.db
      - ./btc-tracker-uploads:/app/public/uploads # Avatars: ./btc-tracker-uploads/
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - btc-tracker-network

networks:
  btc-tracker-network:
    driver: bridge

# ====================================
# Host Directory Examples
# ====================================
# 
# Option 1: Relative paths (current directory)
# volumes:
#   - ./data:/app/data
#   - ./uploads:/app/public/uploads
#
# Option 2: Absolute paths
# volumes:
#   - /home/user/btc-tracker/data:/app/data
#   - /home/user/btc-tracker/uploads:/app/public/uploads
#
# Option 3: Custom locations
# volumes:
#   - /var/lib/btc-tracker:/app/data
#   - /opt/btc-tracker/uploads:/app/public/uploads
#
# Option 4: NAS/Network storage
# volumes:
#   - /mnt/nas/btc-tracker:/app/data
#   - /mnt/nas/btc-tracker/uploads:/app/public/uploads
