version: '3.8'

services:
  btc-tracker:
    image: thewilqq/btc-tracker:latest
    container_name: btc-tracker-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-super-secure-secret-key-here-change-this}
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      # Database storage - automatically created at ./data/btc-tracker.db
      - btc_tracker_data:/app/data
      # Avatar uploads
      - btc_tracker_uploads:/app/public/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - btc-tracker-network

volumes:
  btc_tracker_data:
    driver: local
  btc_tracker_uploads:
    driver: local

networks:
  btc-tracker-network:
    driver: bridge 