name: CI - Test & Build

on:
  push:
    branches: [ "*" ]  # Run on every commit to any branch
  pull_request:
    branches: [ "*" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint code
      run: npm run lint
    
    - name: Setup test database
      run: |
        echo "Setting up test database..."
        npx prisma generate
        npx prisma db push --force-reset
      env:
        DATABASE_URL: "file:./test.db"
        NODE_ENV: test
    
    - name: Run tests
      run: npm run test:ci -- --runInBand --coverage
      env:
        CI: true
        NODE_ENV: test
        DATABASE_URL: "file:./test.db"
        NEXTAUTH_SECRET: "test-secret-key-for-jest-testing-only"
        NEXTAUTH_URL: "http://localhost:3000"
    
    - name: Generate Prisma Client for build
      run: npx prisma generate
      env:
        DATABASE_URL: "file:./prisma/build.db"
    
    - name: Build application
      run: npm run build
      env:
        DATABASE_URL: "file:./prisma/build.db"
        NEXTAUTH_SECRET: "build-time-secret-not-used-in-production"
        NEXTAUTH_URL: "http://localhost:3000"
        NODE_ENV: production
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: success()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov.info
        fail_ci_if_error: false
    
    - name: Build summary
      run: |
        echo "## 🎉 Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Linting passed" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Tests passed" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Build successful" >> $GITHUB_STEP_SUMMARY
        echo "- 📦 Ready for deployment" >> $GITHUB_STEP_SUMMARY
