name: Build and Test

on:
  push:
    branches: [ main, dev, feature/* ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup test database
      run: |
        echo "Setting up test database..."
        npx prisma generate
        npx prisma db push --force-reset
      env:
        DATABASE_URL: "file:./test.db"
        NODE_ENV: test
    
    - name: Run linter
      run: npm run lint
    
    - name: Run tests
      run: npm run test:ci
      env:
        CI: true
        NODE_ENV: test
        DATABASE_URL: "file:./test.db"
        NEXTAUTH_SECRET: "test-secret-key-for-jest-testing-only"
        NEXTAUTH_URL: "http://localhost:3000"
        DISABLE_EXTERNAL_APIS: true
        MOCK_BITCOIN_PRICE: true
        MOCK_EXCHANGE_RATES: true
        TEST_TIMEOUT: 10000
        JEST_VERBOSE: false
    
    - name: Build Next.js app
      run: npm run build
    
    - name: Verify build output
      run: |
        echo "Build completed successfully!"
        ls -la .next/
        echo "Static files:"
        ls -la .next/static/ || echo "No static files yet" 