name: Deploy - Dev Environment

on:
  push:
    branches: [ dev ]
  workflow_run:
    workflows: ["CI - Test & Build"]
    types: [ completed ]
    branches: [ dev ]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    # Only run on push to dev branch and if CI passed
    if: github.ref == 'refs/heads/dev' && (github.event.workflow_run.conclusion == 'success' || github.event_name == 'push')
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_TOKEN }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract commit info
      id: commit
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
    
    - name: Build and push Docker image (dev)
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: |
          thewilqq/btc-tracker:dev
          thewilqq/btc-tracker:dev-${{ steps.commit.outputs.date }}
          thewilqq/btc-tracker:dev-${{ steps.commit.outputs.sha_short }}
        labels: |
          org.opencontainers.image.title=BTC Tracker (Dev)
          org.opencontainers.image.description=Development build of BTC Tracker
          org.opencontainers.image.version=dev-${{ steps.commit.outputs.sha_short }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.url=https://hub.docker.com/r/thewilqq/btc-tracker
          org.opencontainers.image.revision=${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          VERSION=dev-${{ steps.commit.outputs.sha_short }}
          BUILD_DATE=${{ steps.commit.outputs.date }}
          COMMIT_SHA=${{ steps.commit.outputs.sha_short }}
    
    - name: Create deployment summary
      run: |
        echo "## 🚀 Dev Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Environment**: Development" >> $GITHUB_STEP_SUMMARY
        echo "- **Docker Tags**: dev, dev-${{ steps.commit.outputs.date }}, dev-${{ steps.commit.outputs.sha_short }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Platforms**: linux/amd64, linux/arm64, linux/arm/v7" >> $GITHUB_STEP_SUMMARY
        echo "- **Registry**: https://hub.docker.com/r/thewilqq/btc-tracker" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit**: ${{ steps.commit.outputs.sha_short }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch**: ${{ steps.commit.outputs.branch }}" >> $GITHUB_STEP_SUMMARY
